language: ruby

dist: xenial

cache:
  bundler: true

bundler_args: --without debugging

before_script:
  - env
script: bundle exec rake ci

rvm:
  - 2.3

matrix:
  include:
    - rvm: jruby-9.1
      env: "JAVA_OPTS='--add-opens java.base/java.io=jruby --add-opens java.base/sun.nio.ch=jruby'"
        
  fast_finish: true

notifications:
  email:
    - timo.roessner@googlemail.com
    - matijs@matijs.net
    - chastell@chastell.net
  irc: irc.freenode.org#reek

branches:
  only:
    - master
