language: ruby

dist: xenial

cache:
  bundler: true

bundler_args: --without debugging

script: bundle exec rake ci

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  include:
    - rvm: jruby-9.1
      env: "JAVA_OPTS='--add-opens java.base/java.io=jruby --add-opens java.base/sun.nio.ch=jruby'"
        
  fast_finish: true

notifications:
  email:
    - timo.roessner@googlemail.com
    - matijs@matijs.net
    - chastell@chastell.net
  irc: irc.freenode.org#reek

branches:
  only:
    - master
